// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwX_vEsxRVf-e5Pjgn5QZJXd_6V_A1g7w',
    appId: '1:313027415898:web:1aa530b8da46e7ec386d63',
    messagingSenderId: '313027415898',
    projectId: 'digital-shopping-mall-app',
    authDomain: 'digital-shopping-mall-app.firebaseapp.com',
    storageBucket: 'digital-shopping-mall-app.firebasestorage.app',
    measurementId: 'G-SM6LKMJ9L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyWhs0aB5SvZhNbHjdSjW_SiyHiJVoS0',
    appId: '1:313027415898:android:d4da88f920e2df79386d63',
    messagingSenderId: '313027415898',
    projectId: 'digital-shopping-mall-app',
    storageBucket: 'digital-shopping-mall-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtuh1T4J1aBvZyj0i935xrCX1s6s8dHcQ',
    appId: '1:313027415898:ios:0b992323f25f2189386d63',
    messagingSenderId: '313027415898',
    projectId: 'digital-shopping-mall-app',
    storageBucket: 'digital-shopping-mall-app.firebasestorage.app',
    androidClientId: '313027415898-ue9bc38nggnkjd3k0n8gbcpu8eeclepb.apps.googleusercontent.com',
    iosClientId: '313027415898-nkqd1bg52cpifujhl311ntiotki7jgqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtuh1T4J1aBvZyj0i935xrCX1s6s8dHcQ',
    appId: '1:313027415898:ios:0b992323f25f2189386d63',
    messagingSenderId: '313027415898',
    projectId: 'digital-shopping-mall-app',
    storageBucket: 'digital-shopping-mall-app.firebasestorage.app',
    androidClientId: '313027415898-ue9bc38nggnkjd3k0n8gbcpu8eeclepb.apps.googleusercontent.com',
    iosClientId: '313027415898-nkqd1bg52cpifujhl311ntiotki7jgqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwX_vEsxRVf-e5Pjgn5QZJXd_6V_A1g7w',
    appId: '1:313027415898:web:20b5222372dceb0f386d63',
    messagingSenderId: '313027415898',
    projectId: 'digital-shopping-mall-app',
    authDomain: 'digital-shopping-mall-app.firebaseapp.com',
    storageBucket: 'digital-shopping-mall-app.firebasestorage.app',
    measurementId: 'G-P1PPRKW1JB',
  );

}