// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy8gzvcUScu9hj4RaKwsKkp1rZpzy49q4',
    appId: '1:1037643922770:web:02b8d8455d08f2a956ce8b',
    messagingSenderId: '1037643922770',
    projectId: 'pitchaccentapp',
    authDomain: 'pitchaccentapp.firebaseapp.com',
    storageBucket: 'pitchaccentapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQf2fUz-DqPO2AXIUAQV8bR5_C8SQj-I',
    appId: '1:1037643922770:android:4d09703e09419a4456ce8b',
    messagingSenderId: '1037643922770',
    projectId: 'pitchaccentapp',
    storageBucket: 'pitchaccentapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYZtzexfssp-eJFkAku__CaxQ3kbxWAJ8',
    appId: '1:1037643922770:ios:ed89880035172b7856ce8b',
    messagingSenderId: '1037643922770',
    projectId: 'pitchaccentapp',
    storageBucket: 'pitchaccentapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYZtzexfssp-eJFkAku__CaxQ3kbxWAJ8',
    appId: '1:1037643922770:ios:ed89880035172b7856ce8b',
    messagingSenderId: '1037643922770',
    projectId: 'pitchaccentapp',
    storageBucket: 'pitchaccentapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy8gzvcUScu9hj4RaKwsKkp1rZpzy49q4',
    appId: '1:1037643922770:web:37a01f19632d228e56ce8b',
    messagingSenderId: '1037643922770',
    projectId: 'pitchaccentapp',
    authDomain: 'pitchaccentapp.firebaseapp.com',
    storageBucket: 'pitchaccentapp.firebasestorage.app',
  );

}